# Site settings
title: Anthony Edwards Blog
email: anthony.edwardsjr@gmail.com
description: > # this means to ignore newlines until "baseurl:" Welcome! This site is meant to share my thoughts, give insight and explore my journey as a junior software developer. 
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "aedwards12.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
